# Generated by Django 5.2.7 on 2025-10-16 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0001_initial'),
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.profesional'),
        ),
        migrations.AddField(
            model_name='historicalcontrol',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontrol',
            name='profesional',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='login.profesional'),
        ),
        migrations.AddField(
            model_name='historicalperiodocontrol',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nino',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.comuna'),
        ),
        migrations.AddField(
            model_name='historicalcontrol',
            name='nino',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='control.nino'),
        ),
        migrations.AddField(
            model_name='entregaalimentos',
            name='nino',
            field=models.ForeignKey(db_column='rut_nino', on_delete=django.db.models.deletion.CASCADE, to='control.nino'),
        ),
        migrations.AddField(
            model_name='control',
            name='nino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='control.nino'),
        ),
        migrations.AddField(
            model_name='historicalcontrol',
            name='periodo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='control.periodocontrol'),
        ),
        migrations.AddField(
            model_name='control',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control.periodocontrol'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.region'),
        ),
        migrations.AddField(
            model_name='registroalergias',
            name='alergia',
            field=models.ForeignKey(db_column='id_alergia', on_delete=django.db.models.deletion.PROTECT, to='control.alergias'),
        ),
        migrations.AddField(
            model_name='registroalergias',
            name='nino',
            field=models.ForeignKey(db_column='rut_nino', on_delete=django.db.models.deletion.CASCADE, to='control.nino'),
        ),
        migrations.AddField(
            model_name='vacunaaplicada',
            name='nino',
            field=models.ForeignKey(db_column='rut_nino', on_delete=django.db.models.deletion.CASCADE, related_name='vacunas_aplicadas', to='control.nino'),
        ),
        migrations.AddField(
            model_name='vacunaaplicada',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.profesional'),
        ),
        migrations.AddField(
            model_name='vacunaaplicada',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.vacuna'),
        ),
        migrations.AlterUniqueTogether(
            name='registroalergias',
            unique_together={('nino', 'alergia')},
        ),
    ]
