# Generated by Django 5.2.7 on 2025-10-16 06:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_initial'),
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVacunaAplicada',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='vacuna_aplicada_id', db_index=True)),
                ('fecha_programada', models.DateField()),
                ('fecha_aplicacion', models.DateField(blank=True, null=True)),
                ('dosis', models.CharField(blank=True, max_length=50, null=True)),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
                ('negacion', models.BooleanField(default=False)),
                ('via', models.CharField(blank=True, choices=[('I.D', 'Intradérmica'), ('I.M', 'Intramuscular'), ('S.C', 'Subcutánea'), ('V.O', 'Vía Oral'), ('N/A', 'No Aplica')], max_length=10, null=True)),
                ('fecha_inoculacion', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nino', models.ForeignKey(blank=True, db_column='rut_nino', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='control.nino')),
                ('profesional', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='login.profesional')),
                ('vacuna', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='control.vacuna')),
            ],
            options={
                'verbose_name': 'historical vacuna aplicada',
                'verbose_name_plural': 'historical vacuna aplicadas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
