# Generated by Django 5.2.7 on 2025-10-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='estado_seguimiento',
            field=models.CharField(choices=[('ACTIVO', 'Seguimiento Activo'), ('COMPLETADO', 'Programa Completado'), ('TRASLADADO', 'Trasladado/Inactivo'), ('OTRO', 'Otro')], default='ACTIVO', max_length=20, verbose_name='Estado del Seguimiento'),
        ),
        migrations.AddField(
            model_name='nino',
            name='sector',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sector Asignado'),
        ),
    ]
