# Generated by Django 5.2.7 on 2025-10-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_nino_estado_seguimiento_nino_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='deshabilitado',
            field=models.BooleanField(default=False, help_text='Marcar si este control no se realizó o no aplica.'),
        ),
        migrations.AddField(
            model_name='historicalcontrol',
            name='deshabilitado',
            field=models.BooleanField(default=False, help_text='Marcar si este control no se realizó o no aplica.'),
        ),
    ]
