# Generated by Django 5.2.7 on 2025-10-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_control_deshabilitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvacunaaplicada',
            name='deshabilitado',
            field=models.BooleanField(default=False, help_text='Marcar si esta vacuna no aplica o no se realizó.'),
        ),
        migrations.AddField(
            model_name='vacunaaplicada',
            name='deshabilitado',
            field=models.BooleanField(default=False, help_text='Marcar si esta vacuna no aplica o no se realizó.'),
        ),
    ]
