# Generated by Django 5.2.7 on 2025-10-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_historicalvacuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroalergias',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroalergias',
            name='nino',
            field=models.ForeignKey(db_column='rut_nino', on_delete=django.db.models.deletion.CASCADE, related_name='alergias_registradas', to='control.nino'),
        ),
    ]
