# Generated by Django 5.2.7 on 2025-11-02 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_historicalvacunaaplicada_deshabilitado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEnvioReporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('destinatarios', models.TextField(help_text='Lista de correos a los que se envió el reporte, separados por coma.', verbose_name='Destinatarios')),
                ('controles_reportados_count', models.IntegerField(verbose_name='Cantidad de Controles Reportados')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Historial de Envío de Reporte',
                'verbose_name_plural': 'Historial de Envíos de Reportes',
            },
        ),
    ]
