# Generated by Django 5.2.7 on 2025-11-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_historialenvioreporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='fecha_fallecimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fallecimiento'),
        ),
        migrations.AlterField(
            model_name='nino',
            name='estado_seguimiento',
            field=models.CharField(choices=[('ACTIVO', 'Seguimiento Activo'), ('COMPLETADO', 'Programa Completado'), ('TRASLADADO', 'Trasladado/Inactivo'), ('FALLECIDO', 'Fallecido'), ('OTRO', 'Otro')], default='ACTIVO', max_length=20, verbose_name='Estado del Seguimiento'),
        ),
    ]
