# Generated by Django 5.2.7 on 2025-11-02 18:47

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_nino_fecha_fallecimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNino',
            fields=[
                ('rut_nino', models.CharField(db_index=True, max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('ap_paterno', models.CharField(max_length=30)),
                ('ap_materno', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(blank=True, editable=False)),
                ('estado_seguimiento', models.CharField(choices=[('ACTIVO', 'Seguimiento Activo'), ('COMPLETADO', 'Programa Completado'), ('TRASLADADO', 'Trasladado/Inactivo'), ('FALLECIDO', 'Fallecido'), ('OTRO', 'Otro')], default='ACTIVO', max_length=20, verbose_name='Estado del Seguimiento')),
                ('sector', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sector Asignado')),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Fallecimiento')),
                ('nombre_norm', models.CharField(db_index=True, editable=False, max_length=50)),
                ('ap_paterno_norm', models.CharField(db_index=True, editable=False, max_length=30)),
                ('ap_materno_norm', models.CharField(blank=True, db_index=True, editable=False, max_length=30, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('comuna', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='control.comuna')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical nino',
                'verbose_name_plural': 'historical ninos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
