# Generated by Django 5.2.7 on 2025-10-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_historicalalergias'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='ap_materno_norm',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='nino',
            name='ap_paterno_norm',
            field=models.CharField(db_index=True, editable=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='nino',
            name='nombre_norm',
            field=models.CharField(db_index=True, editable=False, max_length=50, null=True),
        ),
    ]
