# Generated by Django 5.2.7 on 2025-10-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_nino_ap_materno_norm_nino_ap_paterno_norm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nino',
            name='ap_paterno_norm',
            field=models.CharField(db_index=True, default='', editable=False, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nino',
            name='nombre_norm',
            field=models.CharField(db_index=True, default='', editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
