# Generated by Django 5.2.7 on 2025-10-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_alter_nino_ap_paterno_norm_alter_nino_nombre_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='notificacion_enviada',
            field=models.BooleanField(default=False, help_text='Indica si ya se envió una notificación de control atrasado.'),
        ),
        migrations.AddField(
            model_name='historicalcontrol',
            name='notificacion_enviada',
            field=models.BooleanField(default=False, help_text='Indica si ya se envió una notificación de control atrasado.'),
        ),
    ]
