# Generated by Django 5.2.7 on 2025-10-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre_completo_norm',
            field=models.CharField(db_index=True, default='', editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
