# Generated by Django 5.2.7 on 2025-10-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_usuario_nombre_completo_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='encargado',
            field=models.BooleanField(default=False),
        ),
    ]
