# Generated by Django 5.2.7 on 2025-10-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_usuario_email_alter_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave_temporal',
            field=models.BooleanField(default=False),
        ),
    ]
